### ISSUE TITLE
all_unique_nos.jsonがないとエラーがでます。こちらのファイルはどこからダウンロードするのでしょうか？

### ISSUE THREAD

**Issue by mumumu09chi** [aih-uth/joint-entity-and-relation-extraction-from-Japanese-case-report-corpus#1]
bash run_joint.shを実行するとall_unique_nos.jsonがないとエラーがでます。all_unique_nos.jsonはどこにあるのでしょうか？

**Comment by daisaku-ss** [comment]
コードをの方を修正しましたので、再度ダウンロードして実行していただけますでしょうか。
よろしくお願いします。

**Comment by mumumu09chi** [comment]
ありがとうございます。
mecabなどのインストールは必要でしょうか？
