### ISSUE TITLE
RuntimeError: The expanded size of the tensor (1158) must match the existing size (512) at non-singleton dimension 1.  Target sizes: [1, 1158].  Tensor sizes: [1, 512]のエラー

### ISSUE THREAD

**Issue by mumumu09chi** [aih-uth/joint-entity-and-relation-extraction-from-Japanese-case-report-corpus#2]
bashを実行すると`RuntimeError: The expanded size of the tensor (1158) must match the existing size (512) at non-singleton dimension 1.  Target sizes: [1, 1158].  Tensor sizes: [1, 512]`でモデルの構築が終了してしまいます。
BERTの入力する単語数には制限があるため最大で510単語として超えるものは除外したとあったのでこのエラーはmecab等の設定で解消されるものでしょうか？現在、mecabのインストールと万病辞書はOSで設定してありますが同じエラーがでます。

**Comment by daisaku-ss** [comment]
ご報告ありがとうございます。
コードの方を修正しましたので、再ダウンロードして実行していただけますでしょうか。
